version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: pdf-parsing-db
    environment:
      POSTGRES_USER: mihasikD
      POSTGRES_PASSWORD: kawabanga1337
      POSTGRES_DB: pdfparsing_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: